apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-luna
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-luna
  template:
    metadata:
      labels:
        app: backend-luna
    spec:
      containers:
        - name: backend-luna
          image: backend-luna:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
